In [ ]:
import pandas as pd

In [ ]:
input_data = pd.read_csv(r"C:\Users\phani\OneDrive\Trainings\spam.csv",
                         encoding="latin",
                         usecols=["Target", "Text"])
input_data.head()

  Target                                               Text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
input_data.shape

(5572, 2)

### Bag of Words Representation

In [ ]:
input_data["Text"]

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                Will Ì_ b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Text, Length: 5572, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vec = CountVectorizer(min_df=0.01, stop_words="english")
vec.fit(input_data["Text"])
transformed_data = vec.transform(input_data["Text"])

In [ ]:
transformed_data

<5572x106 sparse matrix of type '<class 'numpy.int64'>'
	with 12507 stored elements in Compressed Sparse Row format>

In [ ]:
transformed_data = transformed_data.toarray()
print(vec.get_feature_names_out())

['150p' '50' 'amp' 'ask' 'babe' 'buy' 'care' 'cash' 'claim' 'com' 'come'
 'contact' 'cos' 'customer' 'da' 'day' 'dear' 'did' 'doing' 'don' 'dont'
 'feel' 'free' 'going' 'gonna' 'good' 'got' 'great' 'gt' 'happy' 'hey'
 'hi' 'home' 'hope' 'im' 'just' 'know' 'late' 'later' 'let' 'life' 'like'
 'll' 'lol' 'lor' 'love' 'lt' 'make' 'meet' 'message' 'min' 'miss'
 'mobile' 'money' 'morning' 'msg' 'need' 'new' 'nice' 'night' 'number'
 'oh' 'ok' 'phone' 'pick' 'place' 'pls' 'prize' 'really' 'reply' 'right'
 'said' 'say' 'send' 'sent' 'service' 'soon' 'sorry' 'stop' 'sure' 'tell'
 'text' 'thanks' 'thing' 'think' 'time' 'today' 'tomorrow' 'tonight' 'txt'
 'uk' 'ur' 'urgent' 've' 'wait' 'want' 'wat' 'way' 'week' 'win' 'won'
 'work' 'www' 'yeah' 'yes' 'ì_']

In [ ]:
transformed_data_df = pd.DataFrame(transformed_data, columns = vec.get_feature_names_out())

In [ ]:
transformed_data_df

,150p,50,amp,ask,babe,buy,care,cash,claim,com,...,wat,way,week,win,won,work,www,yeah,yes,ì_
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5567,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
5568,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5569,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5570,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5571,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Model Building

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(transformed_data_df,input_data["Target"],test_size=0.33)

In [ ]:
x_train

,150p,50,amp,ask,babe,buy,care,cash,claim,com,...,wat,way,week,win,won,work,www,yeah,yes,ì_
3916,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1437,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4280,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2198,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2345,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5053,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1181,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3557,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2776,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4924,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y_train

3916     ham
1437     ham
4280     ham
2198     ham
2345     ham
        ...
5053    spam
1181     ham
3557     ham
2776     ham
4924     ham
Name: Target, Length: 3733, dtype: object

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [ ]:
clf = RandomForestClassifier()
clf.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
preds = clf.predict(x_test)
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

         ham       0.98      0.98      0.98      1608
        spam       0.87      0.84      0.85       231

    accuracy                           0.96      1839
   macro avg       0.92      0.91      0.92      1839
weighted avg       0.96      0.96      0.96      1839